version: "2"

services:

  esbcore:
    image: ndaidong/zato:cluster
    ports:
      - "8183:8183"
      - "11223:11223"
    entrypoint: |
      bash -c 'bash -s <<EOF
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      echo "Passwords to login Admin Dashboard:"
      cat /opt/zato/web_admin_password /opt/zato/zato_user_password
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      echo "//////////////////////////////////////////////////////////////////"
      /usr/bin/supervisord -c /opt/zato/supervisord.conf
      EOF'
  docsv:
    image: ndaidong/nodeserver
    depends_on:
      - esbcore
    volumes:
      - ./services:/home
    ports:
      - "8185:8185"
      - "8186:8186"
      - "8187:8187"
    environment:
      - NODE_ENV=development
    entrypoint: |
      bash -c 'bash -s <<EOF
      npm install
      npm start
      EOF'
